# Generated by Django 3.2.6 on 2021-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
