# Generated by Django 3.2.6 on 2021-09-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_variants_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='change',
        ),
    ]
